# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PMM\UserBundle\Entity\User: plaintext
        
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CAISSE, ROLE_LABO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOW_TO_SWITCH]
        
    providers:
        main:
            entity:
                class: PMM\UserBundle\Entity\User
                property: username
            
        #in_memory:
            #memory:
                #users:
                    #user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    
    provider: in_memory
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true
            
        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /login
                
    access_control:
