pmm_labo_serologie:
    resource: "@PMMLaboBundle/Resources/config/routing/serologie.yml"
    prefix:   /serologie

pmm_labo_pcvpu:
    resource: "@PMMLaboBundle/Resources/config/routing/pcvpu.yml"
    prefix:   /pcvpu
    
pmm_labo_bulletin:
    resource: "@PMMLaboBundle/Resources/config/routing/bulletin.yml"
    prefix:   /bulletin
    
pmm_labo_formuleleucocytaire:
    resource: "@PMMLaboBundle/Resources/config/routing/formuleleucocytaire.yml"
    prefix:   /formuleleucocytaire
    
pmm_labo_hematologie:
    resource: "@PMMLaboBundle/Resources/config/routing/hematologie.yml"
    prefix:   /hematologie
    
pmm_labo_biochimie:
    resource: "@PMMLaboBundle/Resources/config/routing/biochimie.yml"
    prefix:   /biochimie
    
pmm_labo_ecbucu:
    resource: "@PMMLaboBundle/Resources/config/routing/ecbucu.yml"
    prefix:   /ecbucu
    
pmm_labo_urinelrc:
    resource: "@PMMLaboBundle/Resources/config/routing/urinelrc.yml"
    prefix:   /urinelrc
    
pmm_labo_resultatserologie:
    resource: "@PMMLaboBundle/Resources/config/routing/resultatserologie.yml"
    prefix:   /resultatserologie