services:
    pmm_labo.calcul_amount:
        class: PMM\LaboBundle\CalculAmount\CalculAmount
        tags:
            - { name: doctrine.event_listener, event: prePersist}
            - { name: doctrine.event_listener, event: postPersist}
            
    pmm_labo.creation_resultat_vide:
        class: PMM\LaboBundle\CreationResultatVide\CreationResultatVide
        tags:
            - { name: doctrine.event_listener, event: postPersist}
